name: Release

on:
  push:
    branches:
      - master
    paths:
      # Trigger only when src/** changes
      - ".github/release.json"
      
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.21
     
    - name: Read tag_latest
      id: tag_latest
      uses:  ashley-taylor/read-json-property-action@v1.1
      with:
        path: ./.github/release.json
        property: tag_latest

    - run: make -j build
      env:
        FREEDOM_VERSION: ${{ steps.tag_latest.outputs.value }}
        
    - name: Read description
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/release.info
 
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: V${{steps.tag_latest.outputs.value}}
        name: FreedomGo - v${{steps.tag_latest.outputs.value}}
        body_path: ./.github/release.info
        draft: false
        prerelease: false

    - run: make -j upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_RELEASE_UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}